const authUser = {
  username: "MOE-TR-2041",
  passwordHash:
    "01367509c7d819c7397c16605c5ec3a37d3b0d754583f0b044acdb1466bf78c0b5670118462737979cf7084cd2951d02eaa13492d5328ddd99bc72ccce7da555",
  passwordScheme: "scrypt:n16384:r8:p1:keylen64",
  name: "المستخدم الإداري",
  role: "إدارة التدريب والابتعاث",
};

const trainees = [
  {
    id: 1001,
    name: "سارة العتيبي",
    department: "الموارد البشرية",
    supervisor: "أ. هناء الدوسري",
    startDate: "2025-10-01",
    endDate: "2026-04-05",
    notes: "مستمرة في برنامج التطوير الإداري، وتحتاج اعتماد خطة التسليم النهائية.",
    missingData: false,
  },
  {
    id: 1002,
    name: "محمد الحربي",
    department: "التخطيط",
    supervisor: "م. خالد الشهراني",
    startDate: "2025-09-15",
    endDate: "2026-04-08",
    notes: "تم استكمال التقييم المرحلي، والمتبقي اعتماد التقرير الختامي من المشرف.",
    missingData: false,
  },
  {
    id: 1003,
    name: "ريم القحطاني",
    department: "المالية",
    supervisor: "أ. نوف المطيري",
    startDate: "2025-10-20",
    endDate: "2026-04-13",
    notes: "البرنامج يسير بشكل منتظم مع حاجة لمراجعة ساعات الحضور النهائية.",
    missingData: false,
  },
  {
    id: 1004,
    name: "عبدالله الزهراني",
    department: "التقنية",
    supervisor: "م. علي الغامدي",
    startDate: "2025-11-01",
    endDate: "2026-04-17",
    notes: "ضمن مسار دعم الأنظمة، ويجري إنهاء المهام التطبيقية الأخيرة.",
    missingData: false,
  },
  {
    id: 1005,
    name: "نورة المطيري",
    department: "المتابعة",
    supervisor: "أ. مها الشمري",
    startDate: "2025-11-12",
    endDate: "2026-04-20",
    notes: "يوجد نقص في نموذج المباشرة النهائي وفي نسخة الهوية.",
    missingData: true,
  },
  {
    id: 1006,
    name: "تركي الشهري",
    department: "الدعم الإداري",
    supervisor: "أ. عبدالعزيز القحطاني",
    startDate: "2025-12-03",
    endDate: "2026-04-25",
    notes: "أداء مستقر، والمتبقي تحديث بيانات الاتصال في الملف الإداري.",
    missingData: false,
  },
  {
    id: 1007,
    name: "هند السبيعي",
    department: "التقنية",
    supervisor: "م. لينا اليامي",
    startDate: "2025-12-10",
    endDate: "2026-05-10",
    notes: "مشاركة في فريق التحول الرقمي، مع احتياج لمراجعة خطة التسليم.",
    missingData: false,
  },
  {
    id: 1008,
    name: "فيصل الغامدي",
    department: "المالية",
    supervisor: "أ. رائد العتيبي",
    startDate: "2026-01-05",
    endDate: "2026-05-28",
    notes: "البرنامج يسير وفق الخطة، مع متابعة دورية من الإدارة.",
    missingData: false,
  },
  {
    id: 1009,
    name: "لولوة العمري",
    department: "الموارد البشرية",
    supervisor: "أ. شيخة الدوسري",
    startDate: "2026-01-18",
    endDate: "2026-06-12",
    notes: "بحاجة لإرفاق نسخة محدثة من خطاب الترشيح.",
    missingData: true,
  },
  {
    id: 1010,
    name: "ماجد القحطاني",
    department: "التخطيط",
    supervisor: "م. عبدالله العوفي",
    startDate: "2025-08-20",
    endDate: "2026-03-28",
    notes: "انتهت فترة التدريب وتنتظر الحالة إغلاق الملف واعتماد الإشعار.",
    missingData: false,
  },
  {
    id: 1011,
    name: "أمل العسيري",
    department: "المتابعة",
    supervisor: "أ. هدى الحربي",
    startDate: "2025-09-01",
    endDate: "2026-03-20",
    notes: "حالة منتهية ويجب استكمال أرشفة المستندات المتبقية.",
    missingData: false,
  },
  {
    id: 1012,
    name: "راكان الدوسري",
    department: "الدعم الإداري",
    supervisor: "أ. خالد السهلي",
    startDate: "2026-02-01",
    endDate: "2026-07-07",
    notes: "متدرب نشط ضمن مسار الخدمات المساندة.",
    missingData: false,
  },
  {
    id: 1013,
    name: "ميار العنزي",
    department: "التقنية",
    supervisor: "م. نجلاء الحربي",
    startDate: "2026-02-10",
    endDate: "2026-08-18",
    notes: "تحتاج اعتماد خطة التدريب الفصلية من الإدارة المختصة.",
    missingData: false,
  },
  {
    id: 1014,
    name: "عبدالرحمن البلوي",
    department: "المالية",
    supervisor: "أ. ابتسام الزهراني",
    startDate: "2026-01-22",
    endDate: "2026-09-03",
    notes: "نشط، والمتابعة الحالية تركز على اكتمال التقارير الشهرية.",
    missingData: false,
  },
];

function getPublicAuthUser() {
  return {
    username: authUser.username,
    name: authUser.name,
    role: authUser.role,
  };
}

module.exports = {
  authUser,
  trainees,
  getPublicAuthUser,
};
